version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd@12345678
      POSTGRES_DB: chatapp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  postgres-data:
